const chats = [
    [
        {
            id:1,
            userid:42,
            msg:"hello",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        }, 
        {
            id:2,
            userid:47,
            msg:"hi",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        }, 
        {
            id:3,
            userid:42,
            msg:"what's the weather today in your city",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:4,
            userid:41,
            msg:"mostly sunny, why asking?",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:5,
            userid:42,
            msg:"Im going to come for weekends",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:6,
            userid:47,
            msg:"Cool! waiting for u",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:7,
            userid:42,
            msg:"I have some shit to do on st but ill be free on sn",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:8,
            userid:41,
            msg:"ok, ill come for u on sunday",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:9,
            userid:42,
            msg:"yeah, we coulg see others",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:10,
            userid:42,
            msg:"ill text them",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:11,
            userid:42,
            msg:"hello",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:12,
            userid:41,
            msg:"hi",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:13,
            userid:42,
            msg:"what's the weather today in your city",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:14,
            userid:41,
            msg:"mostly sunny, why asking?",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:15,
            userid:42,
            msg:"Im going to come for weekends",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:16,
            userid:41,
            msg:"Cool! waiting for u",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:17,
            userid:42,
            msg:"I have some shit to do on st but ill be free on sn",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:18,
            userid:47,
            msg:"ok, ill come for u on sunday",
            time:"12:45",
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:19,
            userid:47,
            msg:"never mind",
            time:"12:45",
            
            day:"10",
            month:"11",
            year:"2022",
            small:true,
        },
        {
            id:20,
            userid:41,
            msg:"any text here",
            time:"13:00",
            
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:21,
            userid:42,
            msg:"yeah, we coulg see others",
            time:"13:00",
            
            day:"10",
            month:"11",
            year:"2022",
        },
        {
            id:22,
            userid:42,
            msg:"ill text them",
            time:"13:00",
            
            day:"10",
            month:"11",
            year:"2022",
        },  
    ],
]
module.exports = chats