const chats = [
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
        {
            id:2,
            userid:2,
            msg:"hi",
            time:"12:45"
        }, 
        {
            id:3,
            userid:1,
            msg:"what's the weather today in your city",
            time:"12:45"
        },
        {
            id:4,
            userid:2,
            msg:"mostly sunny, why asking?",
            time:"12:45"
        },
        {
            id:5,
            userid:1,
            msg:"Im going to come for weekends",
            time:"12:45"
        },
        {
            id:6,
            userid:2,
            msg:"Cool! waiting for u",
            time:"12:45"
        },
        {
            id:7,
            userid:1,
            msg:"I have some shit to do on st but ill be free on sn",
            time:"12:45"
        },
        {
            id:8,
            userid:2,
            msg:"ok, ill come for u on sunday",
            time:"12:45"
        },
        {
            id:9,
            userid:1,
            msg:"yeah, we coulg see others",
            time:"12:45"
        },
        {
            id:10,
            userid:1,
            msg:"ill text them",
            time:"12:45"
        },
        {
            id:11,
            userid:1,
            msg:"hello",
            time:"12:45"
        },
        {
            id:12,
            userid:2,
            msg:"hi",
            time:"12:45"
        },
        {
            id:13,
            userid:1,
            msg:"what's the weather today in your city",
            time:"12:45"
        },
        {
            id:14,
            userid:2,
            msg:"mostly sunny, why asking?",
            time:"12:45"
        },
        {
            id:15,
            userid:1,
            msg:"Im going to come for weekends",
            time:"12:45"
        },
        {
            id:16,
            userid:2,
            msg:"Cool! waiting for u",
            time:"12:45"
        },
        {
            id:17,
            userid:1,
            msg:"I have some shit to do on st but ill be free on sn",
            time:"12:45"
        },
        {
            id:18,
            userid:2,
            msg:"ok, ill come for u on sunday",
            time:"12:45"
        },
        {
            id:19,
            userid:2,
            msg:"never mind",
            time:"12:45",
            small:true
        },
        {
            id:20,
            userid:2,
            msg:"any text here",
            time:"13:00"
        },
        {
            id:21,
            userid:1,
            msg:"yeah, we coulg see others",
            time:"13:00"
        },
        {
            id:22,
            userid:1,
            msg:"ill text them",
            time:"13:00"
        },  
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hey",
            time:"12:45"
        },
        {
            id:2,
            userid:1,
            msg:"anybody here?",
            time:"12:45"
        },
        {
            id:3,
            userid:2,
            msg:"im sleeping",
            time:"12:45"
        },
        {
            id:4,
            userid:1,
            msg:"me too but wait",
            time:"12:45"
        },
        {
            id:5,
            userid:1,
            msg:"are you on party tommorow?",
            time:"12:45"
        },
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
    [
        {
            id:1,
            userid:1,
            msg:"hello",
            time:"12:45"
        }, 
    ],
]
module.exports = chats